# HackathonCompetition

In [7]:
## import dataset

In [8]:
import pandas as pd

In [9]:
df=pd.read_csv("crop_yield_prediction_1000.csv")

In [10]:
df

,Rainfall_mm,Fertilizer_kg_per_hectare,Temperature_C,Soil_Type,Yield_ton_per_hectare
0,781.5,133.3,23.3,Loamy,6.01
1,946.9,136.5,14.4,Clay,8.23
2,512.2,104.4,25.4,Loamy,4.90
3,667.3,143.0,30.1,Loamy,7.14
4,779.9,84.2,24.4,Loamy,6.77
...,...,...,...,...,...
995,545.1,82.8,26.1,Loamy,5.70
996,738.7,67.0,25.5,Loamy,5.57
997,721.0,67.3,25.8,Loamy,5.74
998,476.8,85.5,24.2,Clay,6.06
999,926.1,157.6,20.7,Sandy,7.41

In [11]:
df.isnull().sum()

Rainfall_mm                  0
Fertilizer_kg_per_hectare    0
Temperature_C                0
Soil_Type                    0
Yield_ton_per_hectare        0
dtype: int64

In [12]:
df.dtypes

Rainfall_mm                  float64
Fertilizer_kg_per_hectare    float64
Temperature_C                float64
Soil_Type                     object
Yield_ton_per_hectare        float64
dtype: object

In [13]:
# import encoder

In [14]:
from sklearn.preprocessing import LabelEncoder

In [15]:
encoder=LabelEncoder()

In [16]:
encoder

LabelEncoder()

In [17]:
df.columns

Index(['Rainfall_mm', 'Fertilizer_kg_per_hectare', 'Temperature_C',
       'Soil_Type', 'Yield_ton_per_hectare'],
      dtype='object')

In [18]:
df["Soil_Type"]=encoder.fit_transform(df["Soil_Type"])

In [19]:
df.sample()

,Rainfall_mm,Fertilizer_kg_per_hectare,Temperature_C,Soil_Type,Yield_ton_per_hectare
118,347.9,116.9,16.6,2,4.44

In [20]:
# now split data

In [21]:
x=df[['Rainfall_mm', 'Fertilizer_kg_per_hectare', 'Temperature_C','Soil_Type']]
y=df['Yield_ton_per_hectare']

In [22]:
x.sample()

     Rainfall_mm  Fertilizer_kg_per_hectare  Temperature_C  Soil_Type
843       1120.1                      112.7           20.3          0

In [23]:
y.sample()

530    5.91
Name: Yield_ton_per_hectare, dtype: float64

In [24]:
# now train data

In [25]:
from sklearn.model_selection import train_test_split

In [26]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [27]:
x_train.sample()

     Rainfall_mm  Fertilizer_kg_per_hectare  Temperature_C  Soil_Type
791        833.6                      162.1           24.6          0

In [28]:
y_train.sample()

396    9.86
Name: Yield_ton_per_hectare, dtype: float64

In [29]:
from sklearn.linear_model import LinearRegression

In [30]:
model=LinearRegression()

In [31]:
model

LinearRegression()

In [32]:
model.fit(x_train,y_train)

LinearRegression()

In [33]:
model.predict(x_test)

array([ 3.83730823,  5.66691828,  5.49520947,  7.79509929,  9.60735177,
        3.84190535,  6.30075732,  5.31763111,  5.6902665 ,  4.83235151,
        8.35530645,  6.34019334,  5.44075358,  6.29582271,  6.40534668,
        8.5766975 ,  6.57849876,  7.56851805,  7.22312809,  6.12581585,
        4.24640387,  8.09237008,  8.00796005,  4.75117885,  7.20802854,
        7.6848432 ,  7.95877015,  5.35631771,  4.44906664,  5.7084366 ,
        7.8609034 ,  6.58072835, 10.00266432,  5.63458097,  4.29568281,
        6.34083413,  6.15642674,  6.24053405,  7.82915851,  4.61951915,
        5.97843989,  4.78110415,  4.6844574 ,  4.92501731,  6.57554692,
        6.51910201,  7.52869772,  7.63747845,  6.23455594,  4.7868111 ,
        4.30849073,  8.20477624,  5.38833523,  4.54209145,  8.36204442,
        5.74439837,  5.91157183,  5.73653065,  5.55771403,  4.25567394,
        6.68268882,  7.36541608,  7.07347108,  4.72529625,  6.13944957,
        5.13168034,  5.82688073,  7.73328327,  4.07694732,  5.54990959,
        7.7899679 ,  4.57940997,  6.24377515,  4.68672501,  6.60383053,
        3.7314668 ,  5.21537217,  7.01963994,  6.80347545,  7.99553938,
        4.6740791 ,  5.12040434,  7.80549552,  7.93621633,  8.45370606,
        6.14099512,  4.92409216,  6.95676014,  4.80096977,  6.7727536 ,
        6.71165099,  6.15072745,  5.9902889 ,  6.06482739,  6.70455474,
        5.93297145,  4.53778024,  8.14276729,  7.79491572,  8.08629163,
        7.44132732,  5.3486398 ,  4.19937564,  6.95692845,  6.05695521,
        6.72401525,  6.89759093,  5.23702396,  7.26998679,  5.9803572 ,
        6.52809877,  7.88757529,  7.75637653,  4.70795716,  5.55421488,
        5.69572925,  7.60063443,  6.62787265,  5.68420788,  5.34223251,
        8.67820584,  8.27337523,  7.65766804,  5.95400321,  7.19040434,
        6.07302337,  8.24971942,  5.43468273,  7.55448574,  7.09613636,
        8.66531448,  4.65718297,  7.50384629,  5.08638906,  5.94059533,
        6.8769133 ,  6.59051229,  4.28663407,  6.31085243,  6.25208013,
        4.87070466,  5.12679535,  8.28887226,  7.72968643,  6.8768659 ,
        3.60227782,  7.23587069,  8.20126177,  8.71028893,  7.02662489,
        6.97735662,  5.40048824,  7.2577248 ,  7.00543596,  5.59802041,
        5.35815624,  7.46191744,  6.66746859,  6.64463956,  9.39419155,
        4.88622465,  6.55332491,  4.33758864,  7.34324201,  8.60903341,
        3.6247057 ,  3.68722043,  5.59899525,  5.50579782,  6.60083512,
        4.99481911,  7.38295222,  7.98675926,  7.24845099,  7.30749799,
        5.5489514 ,  9.60906857,  5.2860738 ,  7.90389169,  7.58446139,
        6.2798469 ,  5.61716326,  8.97425936,  7.65821273,  6.63268619,
        9.11690848,  7.43788739,  5.44612718,  3.52076012,  4.89753085,
        6.69717974,  6.10873011,  6.15873177,  7.47188303,  4.48128124,
        5.0801642 ,  6.301576  ,  5.70935119,  7.45229113,  7.61759804])

In [34]:
import joblib as jb

In [35]:
jb.dump(model,"crop.pkl")

['crop.pkl']

In [46]:
model.predict([[140,75,29,2]])

d:\anaconda\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([3.30451986])